# To install:
# Vagrant, Ansible, VS Code, Python, Discord, Firefox, Git

# Also to install:
# - https://github.com/josenk/vagrant-vmware-esxi

- name: Network Getting Started First Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks: