- name: CI CD Learning
  gather_facts: true
  hosts: localhost
  connection: local
  tasks:
    - name: Create a file
      ansible.builtin.file:
        path: ./createdFile
        state: present
    
    - name: Add a line
      ansible.builtin.lineinfile:
        path: ./createdFile
        line: "It worked"
        insertafter: EOF