# To install:
# Vagrant, Ansible, Python

# Also to install:
# - https://github.com/josenk/vagrant-vmware-esxi

- name: Update and Upgrade Ubuntu Servers
  gather_facts: false
  hosts: ubuntu
  become: true
  # roles:
  #   - updateandupgrade

  vars_files:
    - ../shhh.yml

  tasks:
    - name: Update and Upgrade
      apt:
        update_cache: true
        upgrade: "yes"

    - name: Reboot the machine, now
      reboot: